FROM osrf/ros:humble-desktop

# Install common tools
RUN apt-get update && apt-get install -y \
    lsb-release wget gnupg software-properties-common \
    && rm -rf /var/lib/apt/lists/* 

# Install gazebo11
RUN add-apt-repository ppa:openrobotics/gazebo11-gz-cli
RUN apt-get update && apt-get install -y \
    gazebo11 \
    ros-humble-gazebo-ros-pkgs \
    && rm -rf /var/lib/apt/lists/* 

# Install Gazebo Harmonic
RUN apt-get update \
    && wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null \
    && apt-get update && apt-get install -y -q \
        gz-harmonic \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT [ "/bin/bash" ]